### ISSUE TITLE
Integration: Unnamed Exchange

### ISSUE THREAD

**Issue by markjkooistra** [coinranking/exchanges#2]
**Name** 
Unnamed Exchange

**Website**
https://www.unnamed.exchange

**API endpoint**
https://api.unnamed.exchange/v1/Public/Ticker

**API documentation**
https://www.unnamed.exchange/Home/Api

**Comment by Mr00HasH** [comment]
https://github.com/coinranking/exchanges/pull/7

**Comment by nickpater** [comment]
Included in #13
