### ISSUE TITLE
Integration: Trexexchange

### ISSUE THREAD

**Issue by tsunami106** [coinranking/exchanges#44]
**Exchange name**
Trexexchange

**Website**
https://app.trexexchange.io

**API endpoint**
API for currencies: https://app.trexexchange.io/api/v2/peatio/public/currencies
API for trade (public): https://app.trexexchange.io/api/v2/peatio/public/markets/tickers
API for markets: https://app.trexexchange.io/api/v2/peatio/public/markets
*API documentation**

https://app.trexexchange.io/api/v2/peatio/public/currencies

**Comment by nickpater** [comment]
API and website hasn't been online for a long time, so I'm closing this one for now!
